[phases.setup]
nixPkgs = ["python312", "poetry"]

[phases.install]
cmds = [
    "poetry config virtualenvs.create false",
    "poetry install --only main --no-interaction --no-ansi"
]

[start]
cmd = "poetry run python -m server.main"

